### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-stepped-progress bundle size difference from 2.0.0 to 589083a548125595eb2582dad851ab09e10fb7b7
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-stepped-progress bundle size difference from 2.0.0 to 1c2cbc55ca674c6babbf8338fb12dac184d1b0d5
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-stepped-progress bundle size difference from 2.0.0 to 795219b12d18e3758aea4be6e8fecb819657c130
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-stepped-progress bundle size difference from 2.0.0 to 5954c728de7574679658078f34df2831325030aa
No significant bundle size differences found.

**Review by notlee — APPROVED** [review]

**Pull request merged**
